# docker-compose.prod.yml
version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: fairway-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: always
    networks:
      - fairway-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fairway-backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      - NODE_ENV=production
      - MONGODB_URI=mongodb://mongodb:27017/fairway_operation_contact
      - JWT_SECRET=${JWT_SECRET}
      - PORT=5000
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_PORT=${EMAIL_PORT}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - EMAIL_FROM=${EMAIL_FROM}
      - FRONTEND_URL=http://localhost
    restart: always
    networks:
      - fairway-network
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:latest
    container_name: fairway-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - fairway-network
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping' )"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  fairway-network:
    driver: bridge

volumes:
  mongodb_data:
